version: '3.4'

services:
  credemprestimoapi:
    image: italopessan/emprestimo-api
    container_name: credemprestimos-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
       - "5000:80" 
    depends_on:
      - sqlserver
    networks:
      - emprestimo
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: emprestimo-database
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "Numsey#2021"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql3
    ports:
      - '1433:1433'
    networks:
      - emprestimo
networks:
  emprestimo:
    driver:  bridge
