// <auto-generated />
using System;
using CredEmprestimo.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CredEmprestimo.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250814005909_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CredEmprestimo.Business.Models.BoletoEmprestimo", b =>
                {
                    b.Property<int>("BoletoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoletoId"));

                    b.Property<DateTime>("DataDePagamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmprestimoId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorDaParcela")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BoletoId");

                    b.HasIndex("EmprestimoId");

                    b.ToTable("BoletoEmprestimo");
                });

            modelBuilder.Entity("CredEmprestimo.Business.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SaldoAtual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("CredEmprestimo.Business.Models.Emprestimo", b =>
                {
                    b.Property<int>("EmprestimoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmprestimoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAquisicaoEmprestimo")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorDaParcela")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorEmprestimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmprestimoId");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("Emprestimo");
                });

            modelBuilder.Entity("CredEmprestimo.Business.Models.Saque", b =>
                {
                    b.Property<int>("SaqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaqueId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataSaque")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorSaque")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaqueId");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("Saque");
                });

            modelBuilder.Entity("CredEmprestimo.Business.Models.BoletoEmprestimo", b =>
                {
                    b.HasOne("CredEmprestimo.Business.Models.Emprestimo", "Emprestimo")
                        .WithMany("BoletoEmprestimo")
                        .HasForeignKey("EmprestimoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprestimo");
                });

            modelBuilder.Entity("CredEmprestimo.Business.Models.Emprestimo", b =>
                {
                    b.HasOne("CredEmprestimo.Business.Models.Cliente", "Cliente")
                        .WithOne("Emprestimo")
                        .HasForeignKey("CredEmprestimo.Business.Models.Emprestimo", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CredEmprestimo.Business.Models.Saque", b =>
                {
                    b.HasOne("CredEmprestimo.Business.Models.Cliente", null)
                        .WithOne("Saque")
                        .HasForeignKey("CredEmprestimo.Business.Models.Saque", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CredEmprestimo.Business.Models.Cliente", b =>
                {
                    b.Navigation("Emprestimo");

                    b.Navigation("Saque");
                });

            modelBuilder.Entity("CredEmprestimo.Business.Models.Emprestimo", b =>
                {
                    b.Navigation("BoletoEmprestimo");
                });
#pragma warning restore 612, 618
        }
    }
}
